# @package _global_

defaults:
  - legged_base

# Env structure
env:
  _target_: humanoidverse_env.envs.motions_task.motions.MotionsTask
  config:
    max_episode_length_s: 10

    termination:
      terminate_by_contact: False # problematic in isaacgym when g1+terrain
      # terminate_by_lin_vel: False
      # terminate_by_ang_vel: False
      terminate_by_gravity: True
      terminate_by_low_height: True
      terminate_by_terminate_history_count: 6

    termination_scales:
      termination_min_base_height : 0.3
      # termination_max_base_vel : 10.0
      # termination_max_base_ang_vel : 5.0
      termination_gravity_x : 0.8
      termination_gravity_y : 0.8

# Globally accessible parameters
log_task_name: motions

eval_overrides:
  env:
    config:
      max_episode_length_s: 100000
