# @package _global_

# Be careful when using _raw, history
obs:
  obs_dict:
    actor_obs: [
      "root_h_obs",
      "local_body_pos",
      "local_body_rot_obs",
      "local_body_vel",
      "local_body_ang_vel"
    ]

  obs_auxiliary:
    short_history: {
    }
  # define those coumpounds in obs_dict, for example, you can define different long/short history with different length
  # obs_auxiliary:

  obs_scales: {
    root_h_obs: 1.0,
    local_body_pos: 1,
    local_body_rot_obs: 1.0,
    local_body_vel: 1.0,
    local_body_ang_vel: 1.0,
  }

  noise_scales: {
    root_h_obs: 0,
    local_body_pos: 0,
    local_body_rot_obs: 0,
    local_body_vel: 0,
    local_body_ang_vel: 0,
  }

  # obs_dims should use list instead of dict
  # will be converted to dict in `pre_process_config`
  obs_dims:
    - root_h_obs: 1
    - local_body_pos:  ${eval:'(${robot.asset.num_mujoco_body} - 1) * 3'}
    - local_body_rot_obs: ${eval:'${robot.asset.num_mujoco_body} * 6'}
    - local_body_vel: ${eval:'${robot.asset.num_mujoco_body} * 3'}
    - local_body_ang_vel: ${eval:'${robot.asset.num_mujoco_body} * 3'}
